import type { Metadata } from "next";
import { Pixelify_Sans } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "digitale",
  description: "Generated by create next app",
};

const pixelify = Pixelify_Sans({
  weight: "400",
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${pixelify.className}`}>
        {children}
      </body>
    </html>
  );
}
