import type { Metadata } from "next";
import { pixelify } from "./fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "digitale",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${pixelify.className}`}>
        {children}
      </body>
    </html>
  );
}
